# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/autoint.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/autoint.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n$easy_rec/python/protos/autoint.proto\x12\x06protos\"\x82\x01\n\x07\x41utoInt\x12\x19\n\x0emulti_head_num\x18\x01 \x02(\r:\x01\x31\x12\x17\n\x0fmulti_head_size\x18\x02 \x02(\r\x12 \n\x15interacting_layer_num\x18\x03 \x02(\r:\x01\x31\x12!\n\x11l2_regularization\x18\x04 \x02(\x02:\x06\x30.0001')
)




_AUTOINT = _descriptor.Descriptor(
  name='AutoInt',
  full_name='protos.AutoInt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='multi_head_num', full_name='protos.AutoInt.multi_head_num', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='multi_head_size', full_name='protos.AutoInt.multi_head_size', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='interacting_layer_num', full_name='protos.AutoInt.interacting_layer_num', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l2_regularization', full_name='protos.AutoInt.l2_regularization', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0.0001),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=179,
)

DESCRIPTOR.message_types_by_name['AutoInt'] = _AUTOINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AutoInt = _reflection.GeneratedProtocolMessageType('AutoInt', (_message.Message,), dict(
  DESCRIPTOR = _AUTOINT,
  __module__ = 'easy_rec.python.protos.autoint_pb2'
  # @@protoc_insertion_point(class_scope:protos.AutoInt)
  ))
_sym_db.RegisterMessage(AutoInt)


# @@protoc_insertion_point(module_scope)
