# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/collaborative_metric_learning.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from easy_rec.python.protos import dnn_pb2 as easy__rec_dot_python_dot_protos_dot_dnn__pb2
from easy_rec.python.protos import layer_pb2 as easy__rec_dot_python_dot_protos_dot_layer__pb2
from easy_rec.python.protos import loss_pb2 as easy__rec_dot_python_dot_protos_dot_loss__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/collaborative_metric_learning.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n:easy_rec/python/protos/collaborative_metric_learning.proto\x12\x06protos\x1a easy_rec/python/protos/dnn.proto\x1a\"easy_rec/python/protos/layer.proto\x1a!easy_rec/python/protos/loss.proto\"\xd9\x02\n\x13\x43oMetricLearningI2I\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12%\n\x07highway\x18\x02 \x03(\x0b\x32\x14.protos.HighWayTower\x12\r\n\x05input\x18\x04 \x01(\t\x12\x18\n\x03\x64nn\x18\x05 \x02(\x0b\x32\x0b.protos.DNN\x12!\n\x11l2_regularization\x18\x06 \x02(\x02:\x06\x30.0001\x12&\n\x18output_l2_normalized_emb\x18\x07 \x02(\x08:\x04true\x12\x11\n\tsample_id\x18\x08 \x01(\t\x12)\n\x0b\x63ircle_loss\x18\x65 \x01(\x0b\x32\x12.protos.CircleLossH\x00\x12<\n\x15multi_similarity_loss\x18\x66 \x01(\x0b\x32\x1b.protos.MultiSimilarityLossH\x00\x12\x0f\n\x07item_id\x18\t \x01(\tB\x06\n\x04loss')
  ,
  dependencies=[easy__rec_dot_python_dot_protos_dot_dnn__pb2.DESCRIPTOR,easy__rec_dot_python_dot_protos_dot_layer__pb2.DESCRIPTOR,easy__rec_dot_python_dot_protos_dot_loss__pb2.DESCRIPTOR,])




_COMETRICLEARNINGI2I = _descriptor.Descriptor(
  name='CoMetricLearningI2I',
  full_name='protos.CoMetricLearningI2I',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_id', full_name='protos.CoMetricLearningI2I.session_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='highway', full_name='protos.CoMetricLearningI2I.highway', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='input', full_name='protos.CoMetricLearningI2I.input', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dnn', full_name='protos.CoMetricLearningI2I.dnn', index=3,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l2_regularization', full_name='protos.CoMetricLearningI2I.l2_regularization', index=4,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0.0001),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_l2_normalized_emb', full_name='protos.CoMetricLearningI2I.output_l2_normalized_emb', index=5,
      number=7, type=8, cpp_type=7, label=2,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sample_id', full_name='protos.CoMetricLearningI2I.sample_id', index=6,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='circle_loss', full_name='protos.CoMetricLearningI2I.circle_loss', index=7,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='multi_similarity_loss', full_name='protos.CoMetricLearningI2I.multi_similarity_loss', index=8,
      number=102, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_id', full_name='protos.CoMetricLearningI2I.item_id', index=9,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='loss', full_name='protos.CoMetricLearningI2I.loss',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=176,
  serialized_end=521,
)

_COMETRICLEARNINGI2I.fields_by_name['highway'].message_type = easy__rec_dot_python_dot_protos_dot_layer__pb2._HIGHWAYTOWER
_COMETRICLEARNINGI2I.fields_by_name['dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_COMETRICLEARNINGI2I.fields_by_name['circle_loss'].message_type = easy__rec_dot_python_dot_protos_dot_loss__pb2._CIRCLELOSS
_COMETRICLEARNINGI2I.fields_by_name['multi_similarity_loss'].message_type = easy__rec_dot_python_dot_protos_dot_loss__pb2._MULTISIMILARITYLOSS
_COMETRICLEARNINGI2I.oneofs_by_name['loss'].fields.append(
  _COMETRICLEARNINGI2I.fields_by_name['circle_loss'])
_COMETRICLEARNINGI2I.fields_by_name['circle_loss'].containing_oneof = _COMETRICLEARNINGI2I.oneofs_by_name['loss']
_COMETRICLEARNINGI2I.oneofs_by_name['loss'].fields.append(
  _COMETRICLEARNINGI2I.fields_by_name['multi_similarity_loss'])
_COMETRICLEARNINGI2I.fields_by_name['multi_similarity_loss'].containing_oneof = _COMETRICLEARNINGI2I.oneofs_by_name['loss']
DESCRIPTOR.message_types_by_name['CoMetricLearningI2I'] = _COMETRICLEARNINGI2I
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CoMetricLearningI2I = _reflection.GeneratedProtocolMessageType('CoMetricLearningI2I', (_message.Message,), dict(
  DESCRIPTOR = _COMETRICLEARNINGI2I,
  __module__ = 'easy_rec.python.protos.collaborative_metric_learning_pb2'
  # @@protoc_insertion_point(class_scope:protos.CoMetricLearningI2I)
  ))
_sym_db.RegisterMessage(CoMetricLearningI2I)


# @@protoc_insertion_point(module_scope)
