# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/data_source.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/data_source.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n(easy_rec/python/protos/data_source.proto\x12\x06protos\"\xa0\x01\n\x0bKafkaServer\x12\x0e\n\x06server\x18\x01 \x02(\t\x12\r\n\x05topic\x18\x02 \x02(\t\x12\r\n\x05group\x18\x03 \x02(\t\x12\x15\n\x0boffset_info\x18( \x01(\tH\x00\x12\x15\n\x0boffset_time\x18* \x01(\tH\x00\x12\x15\n\rconfig_global\x18\x05 \x03(\t\x12\x14\n\x0c\x63onfig_topic\x18\x06 \x03(\tB\x08\n\x06offset\"\x99\x01\n\rDatahubServer\x12\x0c\n\x04\x61kId\x18\x01 \x02(\t\x12\x10\n\x08\x61kSecret\x18\x02 \x02(\t\x12\x10\n\x08\x65ndpoint\x18\x03 \x02(\t\x12\x0f\n\x07project\x18\x04 \x02(\t\x12\r\n\x05topic\x18\x05 \x02(\t\x12\x15\n\x0boffset_info\x18< \x01(\tH\x00\x12\x15\n\x0boffset_time\x18> \x01(\tH\x00\x42\x08\n\x06offset\"P\n\x0f\x42inaryDataInput\x12\x15\n\rcategory_path\x18\x01 \x03(\t\x12\x12\n\ndense_path\x18\x02 \x03(\t\x12\x12\n\nlabel_path\x18\x03 \x03(\t')
)




_KAFKASERVER = _descriptor.Descriptor(
  name='KafkaServer',
  full_name='protos.KafkaServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='server', full_name='protos.KafkaServer.server', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topic', full_name='protos.KafkaServer.topic', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='group', full_name='protos.KafkaServer.group', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offset_info', full_name='protos.KafkaServer.offset_info', index=3,
      number=40, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offset_time', full_name='protos.KafkaServer.offset_time', index=4,
      number=42, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='config_global', full_name='protos.KafkaServer.config_global', index=5,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='config_topic', full_name='protos.KafkaServer.config_topic', index=6,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='offset', full_name='protos.KafkaServer.offset',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=53,
  serialized_end=213,
)


_DATAHUBSERVER = _descriptor.Descriptor(
  name='DatahubServer',
  full_name='protos.DatahubServer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='akId', full_name='protos.DatahubServer.akId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='akSecret', full_name='protos.DatahubServer.akSecret', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='endpoint', full_name='protos.DatahubServer.endpoint', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='project', full_name='protos.DatahubServer.project', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='topic', full_name='protos.DatahubServer.topic', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offset_info', full_name='protos.DatahubServer.offset_info', index=5,
      number=60, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offset_time', full_name='protos.DatahubServer.offset_time', index=6,
      number=62, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='offset', full_name='protos.DatahubServer.offset',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=216,
  serialized_end=369,
)


_BINARYDATAINPUT = _descriptor.Descriptor(
  name='BinaryDataInput',
  full_name='protos.BinaryDataInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='category_path', full_name='protos.BinaryDataInput.category_path', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dense_path', full_name='protos.BinaryDataInput.dense_path', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label_path', full_name='protos.BinaryDataInput.label_path', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=371,
  serialized_end=451,
)

_KAFKASERVER.oneofs_by_name['offset'].fields.append(
  _KAFKASERVER.fields_by_name['offset_info'])
_KAFKASERVER.fields_by_name['offset_info'].containing_oneof = _KAFKASERVER.oneofs_by_name['offset']
_KAFKASERVER.oneofs_by_name['offset'].fields.append(
  _KAFKASERVER.fields_by_name['offset_time'])
_KAFKASERVER.fields_by_name['offset_time'].containing_oneof = _KAFKASERVER.oneofs_by_name['offset']
_DATAHUBSERVER.oneofs_by_name['offset'].fields.append(
  _DATAHUBSERVER.fields_by_name['offset_info'])
_DATAHUBSERVER.fields_by_name['offset_info'].containing_oneof = _DATAHUBSERVER.oneofs_by_name['offset']
_DATAHUBSERVER.oneofs_by_name['offset'].fields.append(
  _DATAHUBSERVER.fields_by_name['offset_time'])
_DATAHUBSERVER.fields_by_name['offset_time'].containing_oneof = _DATAHUBSERVER.oneofs_by_name['offset']
DESCRIPTOR.message_types_by_name['KafkaServer'] = _KAFKASERVER
DESCRIPTOR.message_types_by_name['DatahubServer'] = _DATAHUBSERVER
DESCRIPTOR.message_types_by_name['BinaryDataInput'] = _BINARYDATAINPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KafkaServer = _reflection.GeneratedProtocolMessageType('KafkaServer', (_message.Message,), dict(
  DESCRIPTOR = _KAFKASERVER,
  __module__ = 'easy_rec.python.protos.data_source_pb2'
  # @@protoc_insertion_point(class_scope:protos.KafkaServer)
  ))
_sym_db.RegisterMessage(KafkaServer)

DatahubServer = _reflection.GeneratedProtocolMessageType('DatahubServer', (_message.Message,), dict(
  DESCRIPTOR = _DATAHUBSERVER,
  __module__ = 'easy_rec.python.protos.data_source_pb2'
  # @@protoc_insertion_point(class_scope:protos.DatahubServer)
  ))
_sym_db.RegisterMessage(DatahubServer)

BinaryDataInput = _reflection.GeneratedProtocolMessageType('BinaryDataInput', (_message.Message,), dict(
  DESCRIPTOR = _BINARYDATAINPUT,
  __module__ = 'easy_rec.python.protos.data_source_pb2'
  # @@protoc_insertion_point(class_scope:protos.BinaryDataInput)
  ))
_sym_db.RegisterMessage(BinaryDataInput)


# @@protoc_insertion_point(module_scope)
