# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/dcn.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from easy_rec.python.protos import dnn_pb2 as easy__rec_dot_python_dot_protos_dot_dnn__pb2
from easy_rec.python.protos import tower_pb2 as easy__rec_dot_python_dot_protos_dot_tower__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/dcn.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n easy_rec/python/protos/dcn.proto\x12\x06protos\x1a easy_rec/python/protos/dnn.proto\x1a\"easy_rec/python/protos/tower.proto\"1\n\nCrossTower\x12\r\n\x05input\x18\x01 \x02(\t\x12\x14\n\tcross_num\x18\x02 \x02(\r:\x01\x33\"\x94\x01\n\x03\x44\x43N\x12!\n\ndeep_tower\x18\x01 \x02(\x0b\x32\r.protos.Tower\x12\'\n\x0b\x63ross_tower\x18\x02 \x02(\x0b\x32\x12.protos.CrossTower\x12\x1e\n\tfinal_dnn\x18\x03 \x02(\x0b\x32\x0b.protos.DNN\x12!\n\x11l2_regularization\x18\x05 \x02(\x02:\x06\x30.0001')
  ,
  dependencies=[easy__rec_dot_python_dot_protos_dot_dnn__pb2.DESCRIPTOR,easy__rec_dot_python_dot_protos_dot_tower__pb2.DESCRIPTOR,])




_CROSSTOWER = _descriptor.Descriptor(
  name='CrossTower',
  full_name='protos.CrossTower',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='protos.CrossTower.input', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cross_num', full_name='protos.CrossTower.cross_num', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=163,
)


_DCN = _descriptor.Descriptor(
  name='DCN',
  full_name='protos.DCN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='deep_tower', full_name='protos.DCN.deep_tower', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cross_tower', full_name='protos.DCN.cross_tower', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='final_dnn', full_name='protos.DCN.final_dnn', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l2_regularization', full_name='protos.DCN.l2_regularization', index=3,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0.0001),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=314,
)

_DCN.fields_by_name['deep_tower'].message_type = easy__rec_dot_python_dot_protos_dot_tower__pb2._TOWER
_DCN.fields_by_name['cross_tower'].message_type = _CROSSTOWER
_DCN.fields_by_name['final_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
DESCRIPTOR.message_types_by_name['CrossTower'] = _CROSSTOWER
DESCRIPTOR.message_types_by_name['DCN'] = _DCN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CrossTower = _reflection.GeneratedProtocolMessageType('CrossTower', (_message.Message,), dict(
  DESCRIPTOR = _CROSSTOWER,
  __module__ = 'easy_rec.python.protos.dcn_pb2'
  # @@protoc_insertion_point(class_scope:protos.CrossTower)
  ))
_sym_db.RegisterMessage(CrossTower)

DCN = _reflection.GeneratedProtocolMessageType('DCN', (_message.Message,), dict(
  DESCRIPTOR = _DCN,
  __module__ = 'easy_rec.python.protos.dcn_pb2'
  # @@protoc_insertion_point(class_scope:protos.DCN)
  ))
_sym_db.RegisterMessage(DCN)


# @@protoc_insertion_point(module_scope)
