# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/dlrm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from easy_rec.python.protos import dnn_pb2 as easy__rec_dot_python_dot_protos_dot_dnn__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/dlrm.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n!easy_rec/python/protos/dlrm.proto\x12\x06protos\x1a easy_rec/python/protos/dnn.proto\"\xd6\x01\n\x04\x44LRM\x12\x1c\n\x07top_dnn\x18\x01 \x02(\x0b\x32\x0b.protos.DNN\x12\x1c\n\x07\x62ot_dnn\x18\x02 \x02(\x0b\x32\x0b.protos.DNN\x12 \n\x13\x61rch_interaction_op\x18\x03 \x01(\t:\x03\x64ot\x12&\n\x17\x61rch_interaction_itself\x18\x04 \x01(\x08:\x05\x66\x61lse\x12&\n\x17\x61rch_with_dense_feature\x18\x05 \x01(\x08:\x05\x66\x61lse\x12 \n\x11l2_regularization\x18\n \x01(\x02:\x05\x31\x65-05')
  ,
  dependencies=[easy__rec_dot_python_dot_protos_dot_dnn__pb2.DESCRIPTOR,])




_DLRM = _descriptor.Descriptor(
  name='DLRM',
  full_name='protos.DLRM',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='top_dnn', full_name='protos.DLRM.top_dnn', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bot_dnn', full_name='protos.DLRM.bot_dnn', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='arch_interaction_op', full_name='protos.DLRM.arch_interaction_op', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("dot").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='arch_interaction_itself', full_name='protos.DLRM.arch_interaction_itself', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='arch_with_dense_feature', full_name='protos.DLRM.arch_with_dense_feature', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l2_regularization', full_name='protos.DLRM.l2_regularization', index=5,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1e-05),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=294,
)

_DLRM.fields_by_name['top_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_DLRM.fields_by_name['bot_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
DESCRIPTOR.message_types_by_name['DLRM'] = _DLRM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DLRM = _reflection.GeneratedProtocolMessageType('DLRM', (_message.Message,), dict(
  DESCRIPTOR = _DLRM,
  __module__ = 'easy_rec.python.protos.dlrm_pb2'
  # @@protoc_insertion_point(class_scope:protos.DLRM)
  ))
_sym_db.RegisterMessage(DLRM)


# @@protoc_insertion_point(module_scope)
