# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/dnn.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/dnn.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n easy_rec/python/protos/dnn.proto\x12\x06protos\"h\n\x03\x44NN\x12\x14\n\x0chidden_units\x18\x01 \x03(\r\x12\x15\n\rdropout_ratio\x18\x02 \x03(\x02\x12\x1e\n\nactivation\x18\x03 \x01(\t:\ntf.nn.relu\x12\x14\n\x06use_bn\x18\x04 \x01(\x08:\x04true\"\xb7\x02\n\x03MLP\x12\x14\n\x0chidden_units\x18\x01 \x03(\r\x12\x15\n\rdropout_ratio\x18\x02 \x03(\x02\x12\x18\n\nactivation\x18\x03 \x01(\t:\x04relu\x12\x14\n\x06use_bn\x18\x04 \x01(\x08:\x04true\x12\x1a\n\x0cuse_final_bn\x18\x05 \x01(\x08:\x04true\x12\x1e\n\x10\x66inal_activation\x18\x06 \x01(\t:\x04relu\x12\x17\n\x08use_bias\x18\x07 \x01(\x08:\x05\x66\x61lse\x12\x1f\n\x0binitializer\x18\x08 \x01(\t:\nhe_uniform\x12\x1f\n\x17use_bn_after_activation\x18\t \x01(\x08\x12\x1d\n\x0euse_final_bias\x18\n \x01(\x08:\x05\x66\x61lse\x12\x1d\n\x0e\x61\x64\x64_to_outputs\x18\x0b \x01(\x08:\x05\x66\x61lse')
)




_DNN = _descriptor.Descriptor(
  name='DNN',
  full_name='protos.DNN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hidden_units', full_name='protos.DNN.hidden_units', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dropout_ratio', full_name='protos.DNN.dropout_ratio', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activation', full_name='protos.DNN.activation', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("tf.nn.relu").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_bn', full_name='protos.DNN.use_bn', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=148,
)


_MLP = _descriptor.Descriptor(
  name='MLP',
  full_name='protos.MLP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hidden_units', full_name='protos.MLP.hidden_units', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dropout_ratio', full_name='protos.MLP.dropout_ratio', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='activation', full_name='protos.MLP.activation', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("relu").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_bn', full_name='protos.MLP.use_bn', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_final_bn', full_name='protos.MLP.use_final_bn', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='final_activation', full_name='protos.MLP.final_activation', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("relu").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_bias', full_name='protos.MLP.use_bias', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='initializer', full_name='protos.MLP.initializer', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("he_uniform").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_bn_after_activation', full_name='protos.MLP.use_bn_after_activation', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_final_bias', full_name='protos.MLP.use_final_bias', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='add_to_outputs', full_name='protos.MLP.add_to_outputs', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=462,
)

DESCRIPTOR.message_types_by_name['DNN'] = _DNN
DESCRIPTOR.message_types_by_name['MLP'] = _MLP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DNN = _reflection.GeneratedProtocolMessageType('DNN', (_message.Message,), dict(
  DESCRIPTOR = _DNN,
  __module__ = 'easy_rec.python.protos.dnn_pb2'
  # @@protoc_insertion_point(class_scope:protos.DNN)
  ))
_sym_db.RegisterMessage(DNN)

MLP = _reflection.GeneratedProtocolMessageType('MLP', (_message.Message,), dict(
  DESCRIPTOR = _MLP,
  __module__ = 'easy_rec.python.protos.dnn_pb2'
  # @@protoc_insertion_point(class_scope:protos.MLP)
  ))
_sym_db.RegisterMessage(MLP)


# @@protoc_insertion_point(module_scope)
