# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/dropoutnet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from easy_rec.python.protos import dnn_pb2 as easy__rec_dot_python_dot_protos_dot_dnn__pb2
from easy_rec.python.protos import loss_pb2 as easy__rec_dot_python_dot_protos_dot_loss__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/dropoutnet.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n\'easy_rec/python/protos/dropoutnet.proto\x12\x06protos\x1a easy_rec/python/protos/dnn.proto\x1a!easy_rec/python/protos/loss.proto\"\x81\x03\n\nDropoutNet\x12!\n\x0cuser_content\x18\x01 \x02(\x0b\x32\x0b.protos.DNN\x12$\n\x0fuser_preference\x18\x02 \x02(\x0b\x32\x0b.protos.DNN\x12!\n\x0citem_content\x18\x03 \x02(\x0b\x32\x0b.protos.DNN\x12$\n\x0fitem_preference\x18\x04 \x02(\x0b\x32\x0b.protos.DNN\x12\x1f\n\nuser_tower\x18\x05 \x02(\x0b\x32\x0b.protos.DNN\x12\x1f\n\nitem_tower\x18\x06 \x02(\x0b\x32\x0b.protos.DNN\x12\x1c\n\x11l2_regularization\x18\x07 \x02(\x02:\x01\x30\x12\x1c\n\x11user_dropout_rate\x18\x08 \x02(\x02:\x01\x30\x12\x1e\n\x11item_dropout_rate\x18\t \x02(\x02:\x03\x30.5\x12\x43\n\x0csoftmax_loss\x18\n \x01(\x0b\x32-.protos.SoftmaxCrossEntropyWithNegativeMining')
  ,
  dependencies=[easy__rec_dot_python_dot_protos_dot_dnn__pb2.DESCRIPTOR,easy__rec_dot_python_dot_protos_dot_loss__pb2.DESCRIPTOR,])




_DROPOUTNET = _descriptor.Descriptor(
  name='DropoutNet',
  full_name='protos.DropoutNet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_content', full_name='protos.DropoutNet.user_content', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_preference', full_name='protos.DropoutNet.user_preference', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_content', full_name='protos.DropoutNet.item_content', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_preference', full_name='protos.DropoutNet.item_preference', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_tower', full_name='protos.DropoutNet.user_tower', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_tower', full_name='protos.DropoutNet.item_tower', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l2_regularization', full_name='protos.DropoutNet.l2_regularization', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user_dropout_rate', full_name='protos.DropoutNet.user_dropout_rate', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_dropout_rate', full_name='protos.DropoutNet.item_dropout_rate', index=8,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0.5),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='softmax_loss', full_name='protos.DropoutNet.softmax_loss', index=9,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=506,
)

_DROPOUTNET.fields_by_name['user_content'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_DROPOUTNET.fields_by_name['user_preference'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_DROPOUTNET.fields_by_name['item_content'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_DROPOUTNET.fields_by_name['item_preference'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_DROPOUTNET.fields_by_name['user_tower'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_DROPOUTNET.fields_by_name['item_tower'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_DROPOUTNET.fields_by_name['softmax_loss'].message_type = easy__rec_dot_python_dot_protos_dot_loss__pb2._SOFTMAXCROSSENTROPYWITHNEGATIVEMINING
DESCRIPTOR.message_types_by_name['DropoutNet'] = _DROPOUTNET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DropoutNet = _reflection.GeneratedProtocolMessageType('DropoutNet', (_message.Message,), dict(
  DESCRIPTOR = _DROPOUTNET,
  __module__ = 'easy_rec.python.protos.dropoutnet_pb2'
  # @@protoc_insertion_point(class_scope:protos.DropoutNet)
  ))
_sym_db.RegisterMessage(DropoutNet)


# @@protoc_insertion_point(module_scope)
