# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/esmm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from easy_rec.python.protos import tower_pb2 as easy__rec_dot_python_dot_protos_dot_tower__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/esmm.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n!easy_rec/python/protos/esmm.proto\x12\x06protos\x1a\"easy_rec/python/protos/tower.proto\"\x94\x01\n\x04\x45SMM\x12\x1d\n\x06groups\x18\x01 \x03(\x0b\x32\r.protos.Tower\x12$\n\tctr_tower\x18\x02 \x02(\x0b\x32\x11.protos.TaskTower\x12$\n\tcvr_tower\x18\x03 \x02(\x0b\x32\x11.protos.TaskTower\x12!\n\x11l2_regularization\x18\x04 \x02(\x02:\x06\x30.0001')
  ,
  dependencies=[easy__rec_dot_python_dot_protos_dot_tower__pb2.DESCRIPTOR,])




_ESMM = _descriptor.Descriptor(
  name='ESMM',
  full_name='protos.ESMM',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='groups', full_name='protos.ESMM.groups', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ctr_tower', full_name='protos.ESMM.ctr_tower', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cvr_tower', full_name='protos.ESMM.cvr_tower', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l2_regularization', full_name='protos.ESMM.l2_regularization', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0.0001),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=230,
)

_ESMM.fields_by_name['groups'].message_type = easy__rec_dot_python_dot_protos_dot_tower__pb2._TOWER
_ESMM.fields_by_name['ctr_tower'].message_type = easy__rec_dot_python_dot_protos_dot_tower__pb2._TASKTOWER
_ESMM.fields_by_name['cvr_tower'].message_type = easy__rec_dot_python_dot_protos_dot_tower__pb2._TASKTOWER
DESCRIPTOR.message_types_by_name['ESMM'] = _ESMM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ESMM = _reflection.GeneratedProtocolMessageType('ESMM', (_message.Message,), dict(
  DESCRIPTOR = _ESMM,
  __module__ = 'easy_rec.python.protos.esmm_pb2'
  # @@protoc_insertion_point(class_scope:protos.ESMM)
  ))
_sym_db.RegisterMessage(ESMM)


# @@protoc_insertion_point(module_scope)
