# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/export.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/export.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n#easy_rec/python/protos/export.proto\x12\x06protos\"&\n\x10MultiValueFields\x12\x12\n\ninput_name\x18\x01 \x03(\t\"\xb0\x04\n\x0c\x45xportConfig\x12\x16\n\nbatch_size\x18\x01 \x01(\x05:\x02-1\x12\x1c\n\rexporter_type\x18\x02 \x01(\t:\x05\x66inal\x12!\n\x14\x62\x65st_exporter_metric\x18\x04 \x01(\t:\x03\x61uc\x12\x1b\n\rmetric_bigger\x18\x05 \x01(\x08:\x04true\x12 \n\x11\x65nable_early_stop\x18\x06 \x01(\x08:\x05\x66\x61lse\x12\x18\n\x0f\x65\x61rly_stop_func\x18\xd9\x04 \x01(\t\x12\x1a\n\x11\x65\x61rly_stop_params\x18\xda\x04 \x01(\t\x12\x1e\n\x0fmax_check_steps\x18\x07 \x01(\x05:\x05\x31\x30\x30\x30\x30\x12\x1f\n\x11multi_placeholder\x18\x08 \x01(\x08:\x04true\x12\x1a\n\x0f\x65xports_to_keep\x18\t \x01(\x05:\x01\x31\x12\x34\n\x12multi_value_fields\x18\n \x01(\x0b\x32\x18.protos.MultiValueFields\x12\x1f\n\x10\x61uto_multi_value\x18\x10 \x01(\x08:\x05\x66\x61lse\x12)\n\x1aplaceholder_named_by_input\x18\x0b \x01(\x08:\x05\x66\x61lse\x12\x1b\n\rfilter_inputs\x18\x0c \x01(\x08:\x04true\x12\x1e\n\x0f\x65xport_features\x18\r \x01(\x08:\x05\x66\x61lse\x12!\n\x12\x65xport_rtp_outputs\x18\x0e \x01(\x08:\x05\x66\x61lse\x12\x13\n\x0b\x61sset_files\x18\x0f \x03(\t')
)




_MULTIVALUEFIELDS = _descriptor.Descriptor(
  name='MultiValueFields',
  full_name='protos.MultiValueFields',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_name', full_name='protos.MultiValueFields.input_name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=85,
)


_EXPORTCONFIG = _descriptor.Descriptor(
  name='ExportConfig',
  full_name='protos.ExportConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='protos.ExportConfig.batch_size', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exporter_type', full_name='protos.ExportConfig.exporter_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("final").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='best_exporter_metric', full_name='protos.ExportConfig.best_exporter_metric', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("auc").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metric_bigger', full_name='protos.ExportConfig.metric_bigger', index=3,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='enable_early_stop', full_name='protos.ExportConfig.enable_early_stop', index=4,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='early_stop_func', full_name='protos.ExportConfig.early_stop_func', index=5,
      number=601, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='early_stop_params', full_name='protos.ExportConfig.early_stop_params', index=6,
      number=602, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_check_steps', full_name='protos.ExportConfig.max_check_steps', index=7,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=10000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='multi_placeholder', full_name='protos.ExportConfig.multi_placeholder', index=8,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exports_to_keep', full_name='protos.ExportConfig.exports_to_keep', index=9,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='multi_value_fields', full_name='protos.ExportConfig.multi_value_fields', index=10,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='auto_multi_value', full_name='protos.ExportConfig.auto_multi_value', index=11,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='placeholder_named_by_input', full_name='protos.ExportConfig.placeholder_named_by_input', index=12,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='filter_inputs', full_name='protos.ExportConfig.filter_inputs', index=13,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='export_features', full_name='protos.ExportConfig.export_features', index=14,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='export_rtp_outputs', full_name='protos.ExportConfig.export_rtp_outputs', index=15,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='asset_files', full_name='protos.ExportConfig.asset_files', index=16,
      number=15, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=648,
)

_EXPORTCONFIG.fields_by_name['multi_value_fields'].message_type = _MULTIVALUEFIELDS
DESCRIPTOR.message_types_by_name['MultiValueFields'] = _MULTIVALUEFIELDS
DESCRIPTOR.message_types_by_name['ExportConfig'] = _EXPORTCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MultiValueFields = _reflection.GeneratedProtocolMessageType('MultiValueFields', (_message.Message,), dict(
  DESCRIPTOR = _MULTIVALUEFIELDS,
  __module__ = 'easy_rec.python.protos.export_pb2'
  # @@protoc_insertion_point(class_scope:protos.MultiValueFields)
  ))
_sym_db.RegisterMessage(MultiValueFields)

ExportConfig = _reflection.GeneratedProtocolMessageType('ExportConfig', (_message.Message,), dict(
  DESCRIPTOR = _EXPORTCONFIG,
  __module__ = 'easy_rec.python.protos.export_pb2'
  # @@protoc_insertion_point(class_scope:protos.ExportConfig)
  ))
_sym_db.RegisterMessage(ExportConfig)


# @@protoc_insertion_point(module_scope)
