# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/hive_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/hive_config.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n(easy_rec/python/protos/hive_config.proto\x12\x06protos\"w\n\nHiveConfig\x12\x0c\n\x04host\x18\x01 \x02(\t\x12\x13\n\x04port\x18\x02 \x02(\r:\x05\x31\x30\x30\x30\x30\x12\x17\n\x08username\x18\x03 \x02(\t:\x05\x61\x64min\x12\x19\n\x08\x64\x61tabase\x18\x04 \x02(\t:\x07\x64\x65\x66\x61ult\x12\x12\n\ntable_name\x18\x05 \x02(\t')
)




_HIVECONFIG = _descriptor.Descriptor(
  name='HiveConfig',
  full_name='protos.HiveConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='protos.HiveConfig.host', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='protos.HiveConfig.port', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=10000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='username', full_name='protos.HiveConfig.username', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("admin").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='database', full_name='protos.HiveConfig.database', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=True, default_value=_b("default").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='table_name', full_name='protos.HiveConfig.table_name', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=171,
)

DESCRIPTOR.message_types_by_name['HiveConfig'] = _HIVECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HiveConfig = _reflection.GeneratedProtocolMessageType('HiveConfig', (_message.Message,), dict(
  DESCRIPTOR = _HIVECONFIG,
  __module__ = 'easy_rec.python.protos.hive_config_pb2'
  # @@protoc_insertion_point(class_scope:protos.HiveConfig)
  ))
_sym_db.RegisterMessage(HiveConfig)


# @@protoc_insertion_point(module_scope)
