# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/hyperparams.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/hyperparams.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n(easy_rec/python/protos/hyperparams.proto\x12\x06protos\"\xba\x01\n\x0bRegularizer\x12/\n\x0el1_regularizer\x18\x01 \x01(\x0b\x32\x15.protos.L1RegularizerH\x00\x12/\n\x0el2_regularizer\x18\x02 \x01(\x0b\x32\x15.protos.L2RegularizerH\x00\x12\x34\n\x11l1_l2_regularizer\x18\x03 \x01(\x0b\x32\x17.protos.L1L2RegularizerH\x00\x42\x13\n\x11regularizer_oneof\"!\n\rL1Regularizer\x12\x10\n\x05scale\x18\x01 \x01(\x02:\x01\x31\"!\n\rL2Regularizer\x12\x10\n\x05scale\x18\x01 \x01(\x02:\x01\x31\";\n\x0fL1L2Regularizer\x12\x13\n\x08scale_l1\x18\x01 \x01(\x02:\x01\x31\x12\x13\n\x08scale_l2\x18\x02 \x01(\x02:\x01\x31\"\xb7\x02\n\x0bInitializer\x12J\n\x1ctruncated_normal_initializer\x18\x01 \x01(\x0b\x32\".protos.TruncatedNormalInitializerH\x00\x12\x44\n\x19random_normal_initializer\x18\x02 \x01(\x0b\x32\x1f.protos.RandomNormalInitializerH\x00\x12\x44\n\x19glorot_normal_initializer\x18\x03 \x01(\x0b\x32\x1f.protos.GlorotNormalInitializerH\x00\x12;\n\x14\x63onstant_initializer\x18\x04 \x01(\x0b\x32\x1b.protos.ConstantInitializerH\x00\x42\x13\n\x11initializer_oneof\"@\n\x1aTruncatedNormalInitializer\x12\x0f\n\x04mean\x18\x01 \x01(\x02:\x01\x30\x12\x11\n\x06stddev\x18\x02 \x01(\x02:\x01\x31\"=\n\x17RandomNormalInitializer\x12\x0f\n\x04mean\x18\x01 \x01(\x02:\x01\x30\x12\x11\n\x06stddev\x18\x02 \x01(\x02:\x01\x31\"\x19\n\x17GlorotNormalInitializer\"%\n\x13\x43onstantInitializer\x12\x0e\n\x06\x63onsts\x18\x01 \x03(\x02')
)




_REGULARIZER = _descriptor.Descriptor(
  name='Regularizer',
  full_name='protos.Regularizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='l1_regularizer', full_name='protos.Regularizer.l1_regularizer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l2_regularizer', full_name='protos.Regularizer.l2_regularizer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l1_l2_regularizer', full_name='protos.Regularizer.l1_l2_regularizer', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='regularizer_oneof', full_name='protos.Regularizer.regularizer_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=53,
  serialized_end=239,
)


_L1REGULARIZER = _descriptor.Descriptor(
  name='L1Regularizer',
  full_name='protos.L1Regularizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scale', full_name='protos.L1Regularizer.scale', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=274,
)


_L2REGULARIZER = _descriptor.Descriptor(
  name='L2Regularizer',
  full_name='protos.L2Regularizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scale', full_name='protos.L2Regularizer.scale', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=309,
)


_L1L2REGULARIZER = _descriptor.Descriptor(
  name='L1L2Regularizer',
  full_name='protos.L1L2Regularizer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scale_l1', full_name='protos.L1L2Regularizer.scale_l1', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scale_l2', full_name='protos.L1L2Regularizer.scale_l2', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=370,
)


_INITIALIZER = _descriptor.Descriptor(
  name='Initializer',
  full_name='protos.Initializer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='truncated_normal_initializer', full_name='protos.Initializer.truncated_normal_initializer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='random_normal_initializer', full_name='protos.Initializer.random_normal_initializer', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='glorot_normal_initializer', full_name='protos.Initializer.glorot_normal_initializer', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='constant_initializer', full_name='protos.Initializer.constant_initializer', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='initializer_oneof', full_name='protos.Initializer.initializer_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=373,
  serialized_end=684,
)


_TRUNCATEDNORMALINITIALIZER = _descriptor.Descriptor(
  name='TruncatedNormalInitializer',
  full_name='protos.TruncatedNormalInitializer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mean', full_name='protos.TruncatedNormalInitializer.mean', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stddev', full_name='protos.TruncatedNormalInitializer.stddev', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=686,
  serialized_end=750,
)


_RANDOMNORMALINITIALIZER = _descriptor.Descriptor(
  name='RandomNormalInitializer',
  full_name='protos.RandomNormalInitializer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mean', full_name='protos.RandomNormalInitializer.mean', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stddev', full_name='protos.RandomNormalInitializer.stddev', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=752,
  serialized_end=813,
)


_GLOROTNORMALINITIALIZER = _descriptor.Descriptor(
  name='GlorotNormalInitializer',
  full_name='protos.GlorotNormalInitializer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=815,
  serialized_end=840,
)


_CONSTANTINITIALIZER = _descriptor.Descriptor(
  name='ConstantInitializer',
  full_name='protos.ConstantInitializer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='consts', full_name='protos.ConstantInitializer.consts', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=842,
  serialized_end=879,
)

_REGULARIZER.fields_by_name['l1_regularizer'].message_type = _L1REGULARIZER
_REGULARIZER.fields_by_name['l2_regularizer'].message_type = _L2REGULARIZER
_REGULARIZER.fields_by_name['l1_l2_regularizer'].message_type = _L1L2REGULARIZER
_REGULARIZER.oneofs_by_name['regularizer_oneof'].fields.append(
  _REGULARIZER.fields_by_name['l1_regularizer'])
_REGULARIZER.fields_by_name['l1_regularizer'].containing_oneof = _REGULARIZER.oneofs_by_name['regularizer_oneof']
_REGULARIZER.oneofs_by_name['regularizer_oneof'].fields.append(
  _REGULARIZER.fields_by_name['l2_regularizer'])
_REGULARIZER.fields_by_name['l2_regularizer'].containing_oneof = _REGULARIZER.oneofs_by_name['regularizer_oneof']
_REGULARIZER.oneofs_by_name['regularizer_oneof'].fields.append(
  _REGULARIZER.fields_by_name['l1_l2_regularizer'])
_REGULARIZER.fields_by_name['l1_l2_regularizer'].containing_oneof = _REGULARIZER.oneofs_by_name['regularizer_oneof']
_INITIALIZER.fields_by_name['truncated_normal_initializer'].message_type = _TRUNCATEDNORMALINITIALIZER
_INITIALIZER.fields_by_name['random_normal_initializer'].message_type = _RANDOMNORMALINITIALIZER
_INITIALIZER.fields_by_name['glorot_normal_initializer'].message_type = _GLOROTNORMALINITIALIZER
_INITIALIZER.fields_by_name['constant_initializer'].message_type = _CONSTANTINITIALIZER
_INITIALIZER.oneofs_by_name['initializer_oneof'].fields.append(
  _INITIALIZER.fields_by_name['truncated_normal_initializer'])
_INITIALIZER.fields_by_name['truncated_normal_initializer'].containing_oneof = _INITIALIZER.oneofs_by_name['initializer_oneof']
_INITIALIZER.oneofs_by_name['initializer_oneof'].fields.append(
  _INITIALIZER.fields_by_name['random_normal_initializer'])
_INITIALIZER.fields_by_name['random_normal_initializer'].containing_oneof = _INITIALIZER.oneofs_by_name['initializer_oneof']
_INITIALIZER.oneofs_by_name['initializer_oneof'].fields.append(
  _INITIALIZER.fields_by_name['glorot_normal_initializer'])
_INITIALIZER.fields_by_name['glorot_normal_initializer'].containing_oneof = _INITIALIZER.oneofs_by_name['initializer_oneof']
_INITIALIZER.oneofs_by_name['initializer_oneof'].fields.append(
  _INITIALIZER.fields_by_name['constant_initializer'])
_INITIALIZER.fields_by_name['constant_initializer'].containing_oneof = _INITIALIZER.oneofs_by_name['initializer_oneof']
DESCRIPTOR.message_types_by_name['Regularizer'] = _REGULARIZER
DESCRIPTOR.message_types_by_name['L1Regularizer'] = _L1REGULARIZER
DESCRIPTOR.message_types_by_name['L2Regularizer'] = _L2REGULARIZER
DESCRIPTOR.message_types_by_name['L1L2Regularizer'] = _L1L2REGULARIZER
DESCRIPTOR.message_types_by_name['Initializer'] = _INITIALIZER
DESCRIPTOR.message_types_by_name['TruncatedNormalInitializer'] = _TRUNCATEDNORMALINITIALIZER
DESCRIPTOR.message_types_by_name['RandomNormalInitializer'] = _RANDOMNORMALINITIALIZER
DESCRIPTOR.message_types_by_name['GlorotNormalInitializer'] = _GLOROTNORMALINITIALIZER
DESCRIPTOR.message_types_by_name['ConstantInitializer'] = _CONSTANTINITIALIZER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Regularizer = _reflection.GeneratedProtocolMessageType('Regularizer', (_message.Message,), dict(
  DESCRIPTOR = _REGULARIZER,
  __module__ = 'easy_rec.python.protos.hyperparams_pb2'
  # @@protoc_insertion_point(class_scope:protos.Regularizer)
  ))
_sym_db.RegisterMessage(Regularizer)

L1Regularizer = _reflection.GeneratedProtocolMessageType('L1Regularizer', (_message.Message,), dict(
  DESCRIPTOR = _L1REGULARIZER,
  __module__ = 'easy_rec.python.protos.hyperparams_pb2'
  # @@protoc_insertion_point(class_scope:protos.L1Regularizer)
  ))
_sym_db.RegisterMessage(L1Regularizer)

L2Regularizer = _reflection.GeneratedProtocolMessageType('L2Regularizer', (_message.Message,), dict(
  DESCRIPTOR = _L2REGULARIZER,
  __module__ = 'easy_rec.python.protos.hyperparams_pb2'
  # @@protoc_insertion_point(class_scope:protos.L2Regularizer)
  ))
_sym_db.RegisterMessage(L2Regularizer)

L1L2Regularizer = _reflection.GeneratedProtocolMessageType('L1L2Regularizer', (_message.Message,), dict(
  DESCRIPTOR = _L1L2REGULARIZER,
  __module__ = 'easy_rec.python.protos.hyperparams_pb2'
  # @@protoc_insertion_point(class_scope:protos.L1L2Regularizer)
  ))
_sym_db.RegisterMessage(L1L2Regularizer)

Initializer = _reflection.GeneratedProtocolMessageType('Initializer', (_message.Message,), dict(
  DESCRIPTOR = _INITIALIZER,
  __module__ = 'easy_rec.python.protos.hyperparams_pb2'
  # @@protoc_insertion_point(class_scope:protos.Initializer)
  ))
_sym_db.RegisterMessage(Initializer)

TruncatedNormalInitializer = _reflection.GeneratedProtocolMessageType('TruncatedNormalInitializer', (_message.Message,), dict(
  DESCRIPTOR = _TRUNCATEDNORMALINITIALIZER,
  __module__ = 'easy_rec.python.protos.hyperparams_pb2'
  # @@protoc_insertion_point(class_scope:protos.TruncatedNormalInitializer)
  ))
_sym_db.RegisterMessage(TruncatedNormalInitializer)

RandomNormalInitializer = _reflection.GeneratedProtocolMessageType('RandomNormalInitializer', (_message.Message,), dict(
  DESCRIPTOR = _RANDOMNORMALINITIALIZER,
  __module__ = 'easy_rec.python.protos.hyperparams_pb2'
  # @@protoc_insertion_point(class_scope:protos.RandomNormalInitializer)
  ))
_sym_db.RegisterMessage(RandomNormalInitializer)

GlorotNormalInitializer = _reflection.GeneratedProtocolMessageType('GlorotNormalInitializer', (_message.Message,), dict(
  DESCRIPTOR = _GLOROTNORMALINITIALIZER,
  __module__ = 'easy_rec.python.protos.hyperparams_pb2'
  # @@protoc_insertion_point(class_scope:protos.GlorotNormalInitializer)
  ))
_sym_db.RegisterMessage(GlorotNormalInitializer)

ConstantInitializer = _reflection.GeneratedProtocolMessageType('ConstantInitializer', (_message.Message,), dict(
  DESCRIPTOR = _CONSTANTINITIALIZER,
  __module__ = 'easy_rec.python.protos.hyperparams_pb2'
  # @@protoc_insertion_point(class_scope:protos.ConstantInitializer)
  ))
_sym_db.RegisterMessage(ConstantInitializer)


# @@protoc_insertion_point(module_scope)
