# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/mmoe.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from easy_rec.python.protos import dnn_pb2 as easy__rec_dot_python_dot_protos_dot_dnn__pb2
from easy_rec.python.protos import tower_pb2 as easy__rec_dot_python_dot_protos_dot_tower__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/mmoe.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n!easy_rec/python/protos/mmoe.proto\x12\x06protos\x1a easy_rec/python/protos/dnn.proto\x1a\"easy_rec/python/protos/tower.proto\"<\n\x0b\x45xpertTower\x12\x13\n\x0b\x65xpert_name\x18\x01 \x02(\t\x12\x18\n\x03\x64nn\x18\x02 \x02(\x0b\x32\x0b.protos.DNN\"\xaf\x01\n\x04MMoE\x12$\n\x07\x65xperts\x18\x01 \x03(\x0b\x32\x13.protos.ExpertTower\x12\x1f\n\nexpert_dnn\x18\x02 \x01(\x0b\x32\x0b.protos.DNN\x12\x15\n\nnum_expert\x18\x03 \x01(\r:\x01\x30\x12&\n\x0btask_towers\x18\x04 \x03(\x0b\x32\x11.protos.TaskTower\x12!\n\x11l2_regularization\x18\x05 \x02(\x02:\x06\x30.0001')
  ,
  dependencies=[easy__rec_dot_python_dot_protos_dot_dnn__pb2.DESCRIPTOR,easy__rec_dot_python_dot_protos_dot_tower__pb2.DESCRIPTOR,])




_EXPERTTOWER = _descriptor.Descriptor(
  name='ExpertTower',
  full_name='protos.ExpertTower',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='expert_name', full_name='protos.ExpertTower.expert_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dnn', full_name='protos.ExpertTower.dnn', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=175,
)


_MMOE = _descriptor.Descriptor(
  name='MMoE',
  full_name='protos.MMoE',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='experts', full_name='protos.MMoE.experts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='expert_dnn', full_name='protos.MMoE.expert_dnn', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_expert', full_name='protos.MMoE.num_expert', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_towers', full_name='protos.MMoE.task_towers', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l2_regularization', full_name='protos.MMoE.l2_regularization', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0.0001),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=353,
)

_EXPERTTOWER.fields_by_name['dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_MMOE.fields_by_name['experts'].message_type = _EXPERTTOWER
_MMOE.fields_by_name['expert_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_MMOE.fields_by_name['task_towers'].message_type = easy__rec_dot_python_dot_protos_dot_tower__pb2._TASKTOWER
DESCRIPTOR.message_types_by_name['ExpertTower'] = _EXPERTTOWER
DESCRIPTOR.message_types_by_name['MMoE'] = _MMOE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExpertTower = _reflection.GeneratedProtocolMessageType('ExpertTower', (_message.Message,), dict(
  DESCRIPTOR = _EXPERTTOWER,
  __module__ = 'easy_rec.python.protos.mmoe_pb2'
  # @@protoc_insertion_point(class_scope:protos.ExpertTower)
  ))
_sym_db.RegisterMessage(ExpertTower)

MMoE = _reflection.GeneratedProtocolMessageType('MMoE', (_message.Message,), dict(
  DESCRIPTOR = _MMOE,
  __module__ = 'easy_rec.python.protos.mmoe_pb2'
  # @@protoc_insertion_point(class_scope:protos.MMoE)
  ))
_sym_db.RegisterMessage(MMoE)


# @@protoc_insertion_point(module_scope)
