# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/multi_tower.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from easy_rec.python.protos import dnn_pb2 as easy__rec_dot_python_dot_protos_dot_dnn__pb2
from easy_rec.python.protos import tower_pb2 as easy__rec_dot_python_dot_protos_dot_tower__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/multi_tower.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n(easy_rec/python/protos/multi_tower.proto\x12\x06protos\x1a easy_rec/python/protos/dnn.proto\x1a\"easy_rec/python/protos/tower.proto\"3\n\x08\x44INTower\x12\r\n\x05input\x18\x01 \x02(\t\x12\x18\n\x03\x64nn\x18\x02 \x02(\x0b\x32\x0b.protos.DNN\"I\n\x08\x42STTower\x12\r\n\x05input\x18\x01 \x02(\t\x12\x12\n\x07seq_len\x18\x02 \x02(\r:\x01\x35\x12\x1a\n\x0fmulti_head_size\x18\x03 \x02(\r:\x01\x34\"\xba\x01\n\nMultiTower\x12\x1d\n\x06towers\x18\x01 \x03(\x0b\x32\r.protos.Tower\x12\x1e\n\tfinal_dnn\x18\x04 \x02(\x0b\x32\x0b.protos.DNN\x12!\n\x11l2_regularization\x18\x05 \x02(\x02:\x06\x30.0001\x12$\n\ndin_towers\x18\x06 \x03(\x0b\x32\x10.protos.DINTower\x12$\n\nbst_towers\x18\x07 \x03(\x0b\x32\x10.protos.BSTTower')
  ,
  dependencies=[easy__rec_dot_python_dot_protos_dot_dnn__pb2.DESCRIPTOR,easy__rec_dot_python_dot_protos_dot_tower__pb2.DESCRIPTOR,])




_DINTOWER = _descriptor.Descriptor(
  name='DINTower',
  full_name='protos.DINTower',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='protos.DINTower.input', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dnn', full_name='protos.DINTower.dnn', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=173,
)


_BSTTOWER = _descriptor.Descriptor(
  name='BSTTower',
  full_name='protos.BSTTower',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='protos.BSTTower.input', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seq_len', full_name='protos.BSTTower.seq_len', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=5,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='multi_head_size', full_name='protos.BSTTower.multi_head_size', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=4,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=248,
)


_MULTITOWER = _descriptor.Descriptor(
  name='MultiTower',
  full_name='protos.MultiTower',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='towers', full_name='protos.MultiTower.towers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='final_dnn', full_name='protos.MultiTower.final_dnn', index=1,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l2_regularization', full_name='protos.MultiTower.l2_regularization', index=2,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0.0001),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='din_towers', full_name='protos.MultiTower.din_towers', index=3,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bst_towers', full_name='protos.MultiTower.bst_towers', index=4,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=437,
)

_DINTOWER.fields_by_name['dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_MULTITOWER.fields_by_name['towers'].message_type = easy__rec_dot_python_dot_protos_dot_tower__pb2._TOWER
_MULTITOWER.fields_by_name['final_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_MULTITOWER.fields_by_name['din_towers'].message_type = _DINTOWER
_MULTITOWER.fields_by_name['bst_towers'].message_type = _BSTTOWER
DESCRIPTOR.message_types_by_name['DINTower'] = _DINTOWER
DESCRIPTOR.message_types_by_name['BSTTower'] = _BSTTOWER
DESCRIPTOR.message_types_by_name['MultiTower'] = _MULTITOWER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DINTower = _reflection.GeneratedProtocolMessageType('DINTower', (_message.Message,), dict(
  DESCRIPTOR = _DINTOWER,
  __module__ = 'easy_rec.python.protos.multi_tower_pb2'
  # @@protoc_insertion_point(class_scope:protos.DINTower)
  ))
_sym_db.RegisterMessage(DINTower)

BSTTower = _reflection.GeneratedProtocolMessageType('BSTTower', (_message.Message,), dict(
  DESCRIPTOR = _BSTTOWER,
  __module__ = 'easy_rec.python.protos.multi_tower_pb2'
  # @@protoc_insertion_point(class_scope:protos.BSTTower)
  ))
_sym_db.RegisterMessage(BSTTower)

MultiTower = _reflection.GeneratedProtocolMessageType('MultiTower', (_message.Message,), dict(
  DESCRIPTOR = _MULTITOWER,
  __module__ = 'easy_rec.python.protos.multi_tower_pb2'
  # @@protoc_insertion_point(class_scope:protos.MultiTower)
  ))
_sym_db.RegisterMessage(MultiTower)


# @@protoc_insertion_point(module_scope)
