# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/multi_tower_recall.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from easy_rec.python.protos import dnn_pb2 as easy__rec_dot_python_dot_protos_dot_dnn__pb2
from easy_rec.python.protos import simi_pb2 as easy__rec_dot_python_dot_protos_dot_simi__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/multi_tower_recall.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n/easy_rec/python/protos/multi_tower_recall.proto\x12\x06protos\x1a easy_rec/python/protos/dnn.proto\x1a!easy_rec/python/protos/simi.proto\"\'\n\x0bRecallTower\x12\x18\n\x03\x64nn\x18\x01 \x02(\x0b\x32\x0b.protos.DNN\"\xcf\x01\n\x10MultiTowerRecall\x12\'\n\nuser_tower\x18\x01 \x02(\x0b\x32\x13.protos.RecallTower\x12\'\n\nitem_tower\x18\x02 \x02(\x0b\x32\x13.protos.RecallTower\x12!\n\x11l2_regularization\x18\x03 \x02(\x02:\x06\x30.0001\x12\x1e\n\tfinal_dnn\x18\x04 \x02(\x0b\x32\x0b.protos.DNN\x12&\n\x17ignore_in_batch_neg_sam\x18\n \x02(\x08:\x05\x66\x61lse')
  ,
  dependencies=[easy__rec_dot_python_dot_protos_dot_dnn__pb2.DESCRIPTOR,easy__rec_dot_python_dot_protos_dot_simi__pb2.DESCRIPTOR,])




_RECALLTOWER = _descriptor.Descriptor(
  name='RecallTower',
  full_name='protos.RecallTower',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dnn', full_name='protos.RecallTower.dnn', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=167,
)


_MULTITOWERRECALL = _descriptor.Descriptor(
  name='MultiTowerRecall',
  full_name='protos.MultiTowerRecall',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_tower', full_name='protos.MultiTowerRecall.user_tower', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_tower', full_name='protos.MultiTowerRecall.item_tower', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l2_regularization', full_name='protos.MultiTowerRecall.l2_regularization', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=True, default_value=float(0.0001),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='final_dnn', full_name='protos.MultiTowerRecall.final_dnn', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ignore_in_batch_neg_sam', full_name='protos.MultiTowerRecall.ignore_in_batch_neg_sam', index=4,
      number=10, type=8, cpp_type=7, label=2,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=377,
)

_RECALLTOWER.fields_by_name['dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_MULTITOWERRECALL.fields_by_name['user_tower'].message_type = _RECALLTOWER
_MULTITOWERRECALL.fields_by_name['item_tower'].message_type = _RECALLTOWER
_MULTITOWERRECALL.fields_by_name['final_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
DESCRIPTOR.message_types_by_name['RecallTower'] = _RECALLTOWER
DESCRIPTOR.message_types_by_name['MultiTowerRecall'] = _MULTITOWERRECALL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecallTower = _reflection.GeneratedProtocolMessageType('RecallTower', (_message.Message,), dict(
  DESCRIPTOR = _RECALLTOWER,
  __module__ = 'easy_rec.python.protos.multi_tower_recall_pb2'
  # @@protoc_insertion_point(class_scope:protos.RecallTower)
  ))
_sym_db.RegisterMessage(RecallTower)

MultiTowerRecall = _reflection.GeneratedProtocolMessageType('MultiTowerRecall', (_message.Message,), dict(
  DESCRIPTOR = _MULTITOWERRECALL,
  __module__ = 'easy_rec.python.protos.multi_tower_recall_pb2'
  # @@protoc_insertion_point(class_scope:protos.MultiTowerRecall)
  ))
_sym_db.RegisterMessage(MultiTowerRecall)


# @@protoc_insertion_point(module_scope)
