# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/pdn.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from easy_rec.python.protos import dnn_pb2 as easy__rec_dot_python_dot_protos_dot_dnn__pb2
from easy_rec.python.protos import simi_pb2 as easy__rec_dot_python_dot_protos_dot_simi__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/pdn.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n easy_rec/python/protos/pdn.proto\x12\x06protos\x1a easy_rec/python/protos/dnn.proto\x1a!easy_rec/python/protos/simi.proto\"\xa6\x03\n\x03PDN\x12\x1d\n\x08user_dnn\x18\x01 \x02(\x0b\x32\x0b.protos.DNN\x12\x1d\n\x08item_dnn\x18\x02 \x02(\x0b\x32\x0b.protos.DNN\x12\x1c\n\x07u2i_dnn\x18\x03 \x02(\x0b\x32\x0b.protos.DNN\x12 \n\x0btrigger_dnn\x18\x04 \x02(\x0b\x32\x0b.protos.DNN\x12\x1c\n\x07i2i_dnn\x18\x05 \x02(\x0b\x32\x0b.protos.DNN\x12\x1c\n\x07sim_dnn\x18\x06 \x02(\x0b\x32\x0b.protos.DNN\x12$\n\x0f\x64irect_user_dnn\x18\x07 \x01(\x0b\x32\x0b.protos.DNN\x12$\n\x0f\x64irect_item_dnn\x18\x08 \x01(\x0b\x32\x0b.protos.DNN\x12-\n\tsimi_func\x18\t \x01(\x0e\x32\x12.protos.Similarity:\x06\x43OSINE\x12\x18\n\nscale_simi\x18\n \x01(\x08:\x04true\x12\x1d\n\x08\x62ias_dnn\x18\x0b \x01(\x0b\x32\x0b.protos.DNN\x12\x0f\n\x07item_id\x18\x0c \x01(\t\x12 \n\x11l2_regularization\x18\r \x01(\x02:\x05\x31\x65-06')
  ,
  dependencies=[easy__rec_dot_python_dot_protos_dot_dnn__pb2.DESCRIPTOR,easy__rec_dot_python_dot_protos_dot_simi__pb2.DESCRIPTOR,])




_PDN = _descriptor.Descriptor(
  name='PDN',
  full_name='protos.PDN',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_dnn', full_name='protos.PDN.user_dnn', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_dnn', full_name='protos.PDN.item_dnn', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='u2i_dnn', full_name='protos.PDN.u2i_dnn', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='trigger_dnn', full_name='protos.PDN.trigger_dnn', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='i2i_dnn', full_name='protos.PDN.i2i_dnn', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sim_dnn', full_name='protos.PDN.sim_dnn', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='direct_user_dnn', full_name='protos.PDN.direct_user_dnn', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='direct_item_dnn', full_name='protos.PDN.direct_item_dnn', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='simi_func', full_name='protos.PDN.simi_func', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scale_simi', full_name='protos.PDN.scale_simi', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bias_dnn', full_name='protos.PDN.bias_dnn', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='item_id', full_name='protos.PDN.item_id', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l2_regularization', full_name='protos.PDN.l2_regularization', index=12,
      number=13, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1e-06),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=536,
)

_PDN.fields_by_name['user_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_PDN.fields_by_name['item_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_PDN.fields_by_name['u2i_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_PDN.fields_by_name['trigger_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_PDN.fields_by_name['i2i_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_PDN.fields_by_name['sim_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_PDN.fields_by_name['direct_user_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_PDN.fields_by_name['direct_item_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_PDN.fields_by_name['simi_func'].enum_type = easy__rec_dot_python_dot_protos_dot_simi__pb2._SIMILARITY
_PDN.fields_by_name['bias_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
DESCRIPTOR.message_types_by_name['PDN'] = _PDN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PDN = _reflection.GeneratedProtocolMessageType('PDN', (_message.Message,), dict(
  DESCRIPTOR = _PDN,
  __module__ = 'easy_rec.python.protos.pdn_pb2'
  # @@protoc_insertion_point(class_scope:protos.PDN)
  ))
_sym_db.RegisterMessage(PDN)


# @@protoc_insertion_point(module_scope)
