# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/pipeline.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from easy_rec.python.protos import train_pb2 as easy__rec_dot_python_dot_protos_dot_train__pb2
from easy_rec.python.protos import eval_pb2 as easy__rec_dot_python_dot_protos_dot_eval__pb2
from easy_rec.python.protos import export_pb2 as easy__rec_dot_python_dot_protos_dot_export__pb2
from easy_rec.python.protos import dataset_pb2 as easy__rec_dot_python_dot_protos_dot_dataset__pb2
from easy_rec.python.protos import feature_config_pb2 as easy__rec_dot_python_dot_protos_dot_feature__config__pb2
from easy_rec.python.protos import easy_rec_model_pb2 as easy__rec_dot_python_dot_protos_dot_easy__rec__model__pb2
from easy_rec.python.protos import data_source_pb2 as easy__rec_dot_python_dot_protos_dot_data__source__pb2
from easy_rec.python.protos import hive_config_pb2 as easy__rec_dot_python_dot_protos_dot_hive__config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/pipeline.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n%easy_rec/python/protos/pipeline.proto\x12\x06protos\x1a\"easy_rec/python/protos/train.proto\x1a!easy_rec/python/protos/eval.proto\x1a#easy_rec/python/protos/export.proto\x1a$easy_rec/python/protos/dataset.proto\x1a+easy_rec/python/protos/feature_config.proto\x1a+easy_rec/python/protos/easy_rec_model.proto\x1a(easy_rec/python/protos/data_source.proto\x1a(easy_rec/python/protos/hive_config.proto\"\x9e\x07\n\rEasyRecConfig\x12\x1a\n\x10train_input_path\x18\x01 \x01(\tH\x00\x12\x30\n\x11kafka_train_input\x18\x02 \x01(\x0b\x32\x13.protos.KafkaServerH\x00\x12\x34\n\x13\x64\x61tahub_train_input\x18\x0c \x01(\x0b\x32\x15.protos.DatahubServerH\x00\x12.\n\x10hive_train_input\x18\x65 \x01(\x0b\x32\x12.protos.HiveConfigH\x00\x12\x35\n\x12\x62inary_train_input\x18\x66 \x01(\x0b\x32\x17.protos.BinaryDataInputH\x00\x12\x1d\n\x13parquet_train_input\x18g \x01(\tH\x00\x12\x19\n\x0f\x65val_input_path\x18\x03 \x01(\tH\x01\x12/\n\x10kafka_eval_input\x18\x04 \x01(\x0b\x32\x13.protos.KafkaServerH\x01\x12\x33\n\x12\x64\x61tahub_eval_input\x18\r \x01(\x0b\x32\x15.protos.DatahubServerH\x01\x12.\n\x0fhive_eval_input\x18\xc9\x01 \x01(\x0b\x32\x12.protos.HiveConfigH\x01\x12\x35\n\x11\x62inary_eval_input\x18\xca\x01 \x01(\x0b\x32\x17.protos.BinaryDataInputH\x01\x12\x1d\n\x12parquet_eval_input\x18\xcb\x01 \x01(\tH\x01\x12\x11\n\tmodel_dir\x18\x05 \x02(\t\x12)\n\x0ctrain_config\x18\x06 \x01(\x0b\x32\x13.protos.TrainConfig\x12\'\n\x0b\x65val_config\x18\x07 \x01(\x0b\x32\x12.protos.EvalConfig\x12*\n\x0b\x64\x61ta_config\x18\x08 \x01(\x0b\x32\x15.protos.DatasetConfig\x12.\n\x0f\x66\x65\x61ture_configs\x18\t \x03(\x0b\x32\x15.protos.FeatureConfig\x12/\n\x0e\x66\x65\x61ture_config\x18\n \x01(\x0b\x32\x17.protos.FeatureConfigV2\x12*\n\x0cmodel_config\x18\x0e \x02(\x0b\x32\x14.protos.EasyRecModel\x12+\n\rexport_config\x18\x0f \x01(\x0b\x32\x14.protos.ExportConfig\x12\x14\n\x0c\x66g_json_path\x18\x10 \x01(\tB\x0c\n\ntrain_pathB\x0b\n\teval_path')
  ,
  dependencies=[easy__rec_dot_python_dot_protos_dot_train__pb2.DESCRIPTOR,easy__rec_dot_python_dot_protos_dot_eval__pb2.DESCRIPTOR,easy__rec_dot_python_dot_protos_dot_export__pb2.DESCRIPTOR,easy__rec_dot_python_dot_protos_dot_dataset__pb2.DESCRIPTOR,easy__rec_dot_python_dot_protos_dot_feature__config__pb2.DESCRIPTOR,easy__rec_dot_python_dot_protos_dot_easy__rec__model__pb2.DESCRIPTOR,easy__rec_dot_python_dot_protos_dot_data__source__pb2.DESCRIPTOR,easy__rec_dot_python_dot_protos_dot_hive__config__pb2.DESCRIPTOR,])




_EASYRECCONFIG = _descriptor.Descriptor(
  name='EasyRecConfig',
  full_name='protos.EasyRecConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='train_input_path', full_name='protos.EasyRecConfig.train_input_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kafka_train_input', full_name='protos.EasyRecConfig.kafka_train_input', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datahub_train_input', full_name='protos.EasyRecConfig.datahub_train_input', index=2,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hive_train_input', full_name='protos.EasyRecConfig.hive_train_input', index=3,
      number=101, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='binary_train_input', full_name='protos.EasyRecConfig.binary_train_input', index=4,
      number=102, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parquet_train_input', full_name='protos.EasyRecConfig.parquet_train_input', index=5,
      number=103, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eval_input_path', full_name='protos.EasyRecConfig.eval_input_path', index=6,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kafka_eval_input', full_name='protos.EasyRecConfig.kafka_eval_input', index=7,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datahub_eval_input', full_name='protos.EasyRecConfig.datahub_eval_input', index=8,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='hive_eval_input', full_name='protos.EasyRecConfig.hive_eval_input', index=9,
      number=201, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='binary_eval_input', full_name='protos.EasyRecConfig.binary_eval_input', index=10,
      number=202, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parquet_eval_input', full_name='protos.EasyRecConfig.parquet_eval_input', index=11,
      number=203, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_dir', full_name='protos.EasyRecConfig.model_dir', index=12,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='train_config', full_name='protos.EasyRecConfig.train_config', index=13,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eval_config', full_name='protos.EasyRecConfig.eval_config', index=14,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_config', full_name='protos.EasyRecConfig.data_config', index=15,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature_configs', full_name='protos.EasyRecConfig.feature_configs', index=16,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature_config', full_name='protos.EasyRecConfig.feature_config', index=17,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_config', full_name='protos.EasyRecConfig.model_config', index=18,
      number=14, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='export_config', full_name='protos.EasyRecConfig.export_config', index=19,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fg_json_path', full_name='protos.EasyRecConfig.fg_json_path', index=20,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='train_path', full_name='protos.EasyRecConfig.train_path',
      index=0, containing_type=None, fields=[]),
    _descriptor.OneofDescriptor(
      name='eval_path', full_name='protos.EasyRecConfig.eval_path',
      index=1, containing_type=None, fields=[]),
  ],
  serialized_start=370,
  serialized_end=1296,
)

_EASYRECCONFIG.fields_by_name['kafka_train_input'].message_type = easy__rec_dot_python_dot_protos_dot_data__source__pb2._KAFKASERVER
_EASYRECCONFIG.fields_by_name['datahub_train_input'].message_type = easy__rec_dot_python_dot_protos_dot_data__source__pb2._DATAHUBSERVER
_EASYRECCONFIG.fields_by_name['hive_train_input'].message_type = easy__rec_dot_python_dot_protos_dot_hive__config__pb2._HIVECONFIG
_EASYRECCONFIG.fields_by_name['binary_train_input'].message_type = easy__rec_dot_python_dot_protos_dot_data__source__pb2._BINARYDATAINPUT
_EASYRECCONFIG.fields_by_name['kafka_eval_input'].message_type = easy__rec_dot_python_dot_protos_dot_data__source__pb2._KAFKASERVER
_EASYRECCONFIG.fields_by_name['datahub_eval_input'].message_type = easy__rec_dot_python_dot_protos_dot_data__source__pb2._DATAHUBSERVER
_EASYRECCONFIG.fields_by_name['hive_eval_input'].message_type = easy__rec_dot_python_dot_protos_dot_hive__config__pb2._HIVECONFIG
_EASYRECCONFIG.fields_by_name['binary_eval_input'].message_type = easy__rec_dot_python_dot_protos_dot_data__source__pb2._BINARYDATAINPUT
_EASYRECCONFIG.fields_by_name['train_config'].message_type = easy__rec_dot_python_dot_protos_dot_train__pb2._TRAINCONFIG
_EASYRECCONFIG.fields_by_name['eval_config'].message_type = easy__rec_dot_python_dot_protos_dot_eval__pb2._EVALCONFIG
_EASYRECCONFIG.fields_by_name['data_config'].message_type = easy__rec_dot_python_dot_protos_dot_dataset__pb2._DATASETCONFIG
_EASYRECCONFIG.fields_by_name['feature_configs'].message_type = easy__rec_dot_python_dot_protos_dot_feature__config__pb2._FEATURECONFIG
_EASYRECCONFIG.fields_by_name['feature_config'].message_type = easy__rec_dot_python_dot_protos_dot_feature__config__pb2._FEATURECONFIGV2
_EASYRECCONFIG.fields_by_name['model_config'].message_type = easy__rec_dot_python_dot_protos_dot_easy__rec__model__pb2._EASYRECMODEL
_EASYRECCONFIG.fields_by_name['export_config'].message_type = easy__rec_dot_python_dot_protos_dot_export__pb2._EXPORTCONFIG
_EASYRECCONFIG.oneofs_by_name['train_path'].fields.append(
  _EASYRECCONFIG.fields_by_name['train_input_path'])
_EASYRECCONFIG.fields_by_name['train_input_path'].containing_oneof = _EASYRECCONFIG.oneofs_by_name['train_path']
_EASYRECCONFIG.oneofs_by_name['train_path'].fields.append(
  _EASYRECCONFIG.fields_by_name['kafka_train_input'])
_EASYRECCONFIG.fields_by_name['kafka_train_input'].containing_oneof = _EASYRECCONFIG.oneofs_by_name['train_path']
_EASYRECCONFIG.oneofs_by_name['train_path'].fields.append(
  _EASYRECCONFIG.fields_by_name['datahub_train_input'])
_EASYRECCONFIG.fields_by_name['datahub_train_input'].containing_oneof = _EASYRECCONFIG.oneofs_by_name['train_path']
_EASYRECCONFIG.oneofs_by_name['train_path'].fields.append(
  _EASYRECCONFIG.fields_by_name['hive_train_input'])
_EASYRECCONFIG.fields_by_name['hive_train_input'].containing_oneof = _EASYRECCONFIG.oneofs_by_name['train_path']
_EASYRECCONFIG.oneofs_by_name['train_path'].fields.append(
  _EASYRECCONFIG.fields_by_name['binary_train_input'])
_EASYRECCONFIG.fields_by_name['binary_train_input'].containing_oneof = _EASYRECCONFIG.oneofs_by_name['train_path']
_EASYRECCONFIG.oneofs_by_name['train_path'].fields.append(
  _EASYRECCONFIG.fields_by_name['parquet_train_input'])
_EASYRECCONFIG.fields_by_name['parquet_train_input'].containing_oneof = _EASYRECCONFIG.oneofs_by_name['train_path']
_EASYRECCONFIG.oneofs_by_name['eval_path'].fields.append(
  _EASYRECCONFIG.fields_by_name['eval_input_path'])
_EASYRECCONFIG.fields_by_name['eval_input_path'].containing_oneof = _EASYRECCONFIG.oneofs_by_name['eval_path']
_EASYRECCONFIG.oneofs_by_name['eval_path'].fields.append(
  _EASYRECCONFIG.fields_by_name['kafka_eval_input'])
_EASYRECCONFIG.fields_by_name['kafka_eval_input'].containing_oneof = _EASYRECCONFIG.oneofs_by_name['eval_path']
_EASYRECCONFIG.oneofs_by_name['eval_path'].fields.append(
  _EASYRECCONFIG.fields_by_name['datahub_eval_input'])
_EASYRECCONFIG.fields_by_name['datahub_eval_input'].containing_oneof = _EASYRECCONFIG.oneofs_by_name['eval_path']
_EASYRECCONFIG.oneofs_by_name['eval_path'].fields.append(
  _EASYRECCONFIG.fields_by_name['hive_eval_input'])
_EASYRECCONFIG.fields_by_name['hive_eval_input'].containing_oneof = _EASYRECCONFIG.oneofs_by_name['eval_path']
_EASYRECCONFIG.oneofs_by_name['eval_path'].fields.append(
  _EASYRECCONFIG.fields_by_name['binary_eval_input'])
_EASYRECCONFIG.fields_by_name['binary_eval_input'].containing_oneof = _EASYRECCONFIG.oneofs_by_name['eval_path']
_EASYRECCONFIG.oneofs_by_name['eval_path'].fields.append(
  _EASYRECCONFIG.fields_by_name['parquet_eval_input'])
_EASYRECCONFIG.fields_by_name['parquet_eval_input'].containing_oneof = _EASYRECCONFIG.oneofs_by_name['eval_path']
DESCRIPTOR.message_types_by_name['EasyRecConfig'] = _EASYRECCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EasyRecConfig = _reflection.GeneratedProtocolMessageType('EasyRecConfig', (_message.Message,), dict(
  DESCRIPTOR = _EASYRECCONFIG,
  __module__ = 'easy_rec.python.protos.pipeline_pb2'
  # @@protoc_insertion_point(class_scope:protos.EasyRecConfig)
  ))
_sym_db.RegisterMessage(EasyRecConfig)


# @@protoc_insertion_point(module_scope)
