# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/rocket_launching.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from easy_rec.python.protos import dnn_pb2 as easy__rec_dot_python_dot_protos_dot_dnn__pb2
from easy_rec.python.protos import simi_pb2 as easy__rec_dot_python_dot_protos_dot_simi__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/rocket_launching.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n-easy_rec/python/protos/rocket_launching.proto\x12\x06protos\x1a easy_rec/python/protos/dnn.proto\x1a!easy_rec/python/protos/simi.proto\"\x84\x02\n\x0fRocketLaunching\x12\x1e\n\tshare_dnn\x18\x01 \x02(\x0b\x32\x0b.protos.DNN\x12 \n\x0b\x62ooster_dnn\x18\x02 \x02(\x0b\x32\x0b.protos.DNN\x12\x1e\n\tlight_dnn\x18\x03 \x02(\x0b\x32\x0b.protos.DNN\x12!\n\x11l2_regularization\x18\x04 \x01(\x02:\x06\x30.0001\x12)\n\x1a\x66\x65\x61ture_based_distillation\x18\x05 \x01(\x08:\x05\x66\x61lse\x12\x41\n\x1d\x66\x65\x61ture_distillation_function\x18\x06 \x01(\x0e\x32\x12.protos.Similarity:\x06\x43OSINE')
  ,
  dependencies=[easy__rec_dot_python_dot_protos_dot_dnn__pb2.DESCRIPTOR,easy__rec_dot_python_dot_protos_dot_simi__pb2.DESCRIPTOR,])




_ROCKETLAUNCHING = _descriptor.Descriptor(
  name='RocketLaunching',
  full_name='protos.RocketLaunching',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='share_dnn', full_name='protos.RocketLaunching.share_dnn', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='booster_dnn', full_name='protos.RocketLaunching.booster_dnn', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='light_dnn', full_name='protos.RocketLaunching.light_dnn', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l2_regularization', full_name='protos.RocketLaunching.l2_regularization', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.0001),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature_based_distillation', full_name='protos.RocketLaunching.feature_based_distillation', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='feature_distillation_function', full_name='protos.RocketLaunching.feature_distillation_function', index=5,
      number=6, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=127,
  serialized_end=387,
)

_ROCKETLAUNCHING.fields_by_name['share_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_ROCKETLAUNCHING.fields_by_name['booster_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_ROCKETLAUNCHING.fields_by_name['light_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_ROCKETLAUNCHING.fields_by_name['feature_distillation_function'].enum_type = easy__rec_dot_python_dot_protos_dot_simi__pb2._SIMILARITY
DESCRIPTOR.message_types_by_name['RocketLaunching'] = _ROCKETLAUNCHING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RocketLaunching = _reflection.GeneratedProtocolMessageType('RocketLaunching', (_message.Message,), dict(
  DESCRIPTOR = _ROCKETLAUNCHING,
  __module__ = 'easy_rec.python.protos.rocket_launching_pb2'
  # @@protoc_insertion_point(class_scope:protos.RocketLaunching)
  ))
_sym_db.RegisterMessage(RocketLaunching)


# @@protoc_insertion_point(module_scope)
