# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/simi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/simi.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n!easy_rec/python/protos/simi.proto\x12\x06protos*7\n\nSimilarity\x12\n\n\x06\x43OSINE\x10\x00\x12\x11\n\rINNER_PRODUCT\x10\x01\x12\n\n\x06\x45UCLID\x10\x02')
)

_SIMILARITY = _descriptor.EnumDescriptor(
  name='Similarity',
  full_name='protos.Similarity',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COSINE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INNER_PRODUCT', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EUCLID', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=45,
  serialized_end=100,
)
_sym_db.RegisterEnumDescriptor(_SIMILARITY)

Similarity = enum_type_wrapper.EnumTypeWrapper(_SIMILARITY)
COSINE = 0
INNER_PRODUCT = 1
EUCLID = 2


DESCRIPTOR.enum_types_by_name['Similarity'] = _SIMILARITY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
