# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/tower.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from easy_rec.python.protos import eval_pb2 as easy__rec_dot_python_dot_protos_dot_eval__pb2
from easy_rec.python.protos import loss_pb2 as easy__rec_dot_python_dot_protos_dot_loss__pb2
from easy_rec.python.protos import dnn_pb2 as easy__rec_dot_python_dot_protos_dot_dnn__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/tower.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n\"easy_rec/python/protos/tower.proto\x12\x06protos\x1a!easy_rec/python/protos/eval.proto\x1a!easy_rec/python/protos/loss.proto\x1a easy_rec/python/protos/dnn.proto\"0\n\x05Tower\x12\r\n\x05input\x18\x01 \x02(\t\x12\x18\n\x03\x64nn\x18\x02 \x02(\x0b\x32\x0b.protos.DNN\"\xc2\x03\n\tTaskTower\x12\x12\n\ntower_name\x18\x01 \x02(\t\x12\x12\n\nlabel_name\x18\x02 \x01(\t\x12(\n\x0bmetrics_set\x18\x03 \x03(\x0b\x32\x13.protos.EvalMetrics\x12\x33\n\tloss_type\x18\x04 \x01(\x0e\x32\x10.protos.LossType:\x0e\x43LASSIFICATION\x12\x14\n\tnum_class\x18\x05 \x01(\r:\x01\x31\x12\x18\n\x03\x64nn\x18\x06 \x01(\x0b\x32\x0b.protos.DNN\x12\x11\n\x06weight\x18\x07 \x01(\x02:\x01\x31\x12\"\n\x1atask_space_indicator_label\x18\n \x01(\t\x12\x1f\n\x14in_task_space_weight\x18\x0b \x01(\x02:\x01\x31\x12 \n\x15out_task_space_weight\x18\x0c \x01(\x02:\x01\x31\x12\x1c\n\x06losses\x18\r \x03(\x0b\x32\x0c.protos.Loss\x12\x1f\n\x11use_sample_weight\x18\x0e \x02(\x08:\x04true\x12!\n\x19task_space_indicator_name\x18\x0f \x01(\t\x12\"\n\x1atask_space_indicator_value\x18\x10 \x01(\t\"\x88\x04\n\x0e\x42\x61yesTaskTower\x12\x12\n\ntower_name\x18\x01 \x02(\t\x12\x12\n\nlabel_name\x18\x02 \x01(\t\x12(\n\x0bmetrics_set\x18\x03 \x03(\x0b\x32\x13.protos.EvalMetrics\x12\x33\n\tloss_type\x18\x04 \x01(\x0e\x32\x10.protos.LossType:\x0e\x43LASSIFICATION\x12\x14\n\tnum_class\x18\x05 \x01(\r:\x01\x31\x12\x18\n\x03\x64nn\x18\x06 \x01(\x0b\x32\x0b.protos.DNN\x12\x1c\n\x14relation_tower_names\x18\x07 \x03(\t\x12!\n\x0crelation_dnn\x18\x08 \x01(\x0b\x32\x0b.protos.DNN\x12\x11\n\x06weight\x18\t \x01(\x02:\x01\x31\x12\"\n\x1atask_space_indicator_label\x18\n \x01(\t\x12\x1f\n\x14in_task_space_weight\x18\x0b \x01(\x02:\x01\x31\x12 \n\x15out_task_space_weight\x18\x0c \x01(\x02:\x01\x31\x12\x1c\n\x06losses\x18\x0f \x03(\x0b\x32\x0c.protos.Loss\x12\x1f\n\x11use_sample_weight\x18\x10 \x02(\x08:\x04true\x12!\n\x19task_space_indicator_name\x18\x11 \x01(\t\x12\"\n\x1atask_space_indicator_value\x18\x12 \x01(\t')
  ,
  dependencies=[easy__rec_dot_python_dot_protos_dot_eval__pb2.DESCRIPTOR,easy__rec_dot_python_dot_protos_dot_loss__pb2.DESCRIPTOR,easy__rec_dot_python_dot_protos_dot_dnn__pb2.DESCRIPTOR,])




_TOWER = _descriptor.Descriptor(
  name='Tower',
  full_name='protos.Tower',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input', full_name='protos.Tower.input', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dnn', full_name='protos.Tower.dnn', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=198,
)


_TASKTOWER = _descriptor.Descriptor(
  name='TaskTower',
  full_name='protos.TaskTower',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tower_name', full_name='protos.TaskTower.tower_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label_name', full_name='protos.TaskTower.label_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metrics_set', full_name='protos.TaskTower.metrics_set', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loss_type', full_name='protos.TaskTower.loss_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_class', full_name='protos.TaskTower.num_class', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dnn', full_name='protos.TaskTower.dnn', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='protos.TaskTower.weight', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_space_indicator_label', full_name='protos.TaskTower.task_space_indicator_label', index=7,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='in_task_space_weight', full_name='protos.TaskTower.in_task_space_weight', index=8,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='out_task_space_weight', full_name='protos.TaskTower.out_task_space_weight', index=9,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='losses', full_name='protos.TaskTower.losses', index=10,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_sample_weight', full_name='protos.TaskTower.use_sample_weight', index=11,
      number=14, type=8, cpp_type=7, label=2,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_space_indicator_name', full_name='protos.TaskTower.task_space_indicator_name', index=12,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_space_indicator_value', full_name='protos.TaskTower.task_space_indicator_value', index=13,
      number=16, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=651,
)


_BAYESTASKTOWER = _descriptor.Descriptor(
  name='BayesTaskTower',
  full_name='protos.BayesTaskTower',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tower_name', full_name='protos.BayesTaskTower.tower_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='label_name', full_name='protos.BayesTaskTower.label_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='metrics_set', full_name='protos.BayesTaskTower.metrics_set', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='loss_type', full_name='protos.BayesTaskTower.loss_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_class', full_name='protos.BayesTaskTower.num_class', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dnn', full_name='protos.BayesTaskTower.dnn', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='relation_tower_names', full_name='protos.BayesTaskTower.relation_tower_names', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='relation_dnn', full_name='protos.BayesTaskTower.relation_dnn', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='protos.BayesTaskTower.weight', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_space_indicator_label', full_name='protos.BayesTaskTower.task_space_indicator_label', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='in_task_space_weight', full_name='protos.BayesTaskTower.in_task_space_weight', index=10,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='out_task_space_weight', full_name='protos.BayesTaskTower.out_task_space_weight', index=11,
      number=12, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='losses', full_name='protos.BayesTaskTower.losses', index=12,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_sample_weight', full_name='protos.BayesTaskTower.use_sample_weight', index=13,
      number=16, type=8, cpp_type=7, label=2,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_space_indicator_name', full_name='protos.BayesTaskTower.task_space_indicator_name', index=14,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_space_indicator_value', full_name='protos.BayesTaskTower.task_space_indicator_value', index=15,
      number=18, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=654,
  serialized_end=1174,
)

_TOWER.fields_by_name['dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_TASKTOWER.fields_by_name['metrics_set'].message_type = easy__rec_dot_python_dot_protos_dot_eval__pb2._EVALMETRICS
_TASKTOWER.fields_by_name['loss_type'].enum_type = easy__rec_dot_python_dot_protos_dot_loss__pb2._LOSSTYPE
_TASKTOWER.fields_by_name['dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_TASKTOWER.fields_by_name['losses'].message_type = easy__rec_dot_python_dot_protos_dot_loss__pb2._LOSS
_BAYESTASKTOWER.fields_by_name['metrics_set'].message_type = easy__rec_dot_python_dot_protos_dot_eval__pb2._EVALMETRICS
_BAYESTASKTOWER.fields_by_name['loss_type'].enum_type = easy__rec_dot_python_dot_protos_dot_loss__pb2._LOSSTYPE
_BAYESTASKTOWER.fields_by_name['dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_BAYESTASKTOWER.fields_by_name['relation_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_BAYESTASKTOWER.fields_by_name['losses'].message_type = easy__rec_dot_python_dot_protos_dot_loss__pb2._LOSS
DESCRIPTOR.message_types_by_name['Tower'] = _TOWER
DESCRIPTOR.message_types_by_name['TaskTower'] = _TASKTOWER
DESCRIPTOR.message_types_by_name['BayesTaskTower'] = _BAYESTASKTOWER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Tower = _reflection.GeneratedProtocolMessageType('Tower', (_message.Message,), dict(
  DESCRIPTOR = _TOWER,
  __module__ = 'easy_rec.python.protos.tower_pb2'
  # @@protoc_insertion_point(class_scope:protos.Tower)
  ))
_sym_db.RegisterMessage(Tower)

TaskTower = _reflection.GeneratedProtocolMessageType('TaskTower', (_message.Message,), dict(
  DESCRIPTOR = _TASKTOWER,
  __module__ = 'easy_rec.python.protos.tower_pb2'
  # @@protoc_insertion_point(class_scope:protos.TaskTower)
  ))
_sym_db.RegisterMessage(TaskTower)

BayesTaskTower = _reflection.GeneratedProtocolMessageType('BayesTaskTower', (_message.Message,), dict(
  DESCRIPTOR = _BAYESTASKTOWER,
  __module__ = 'easy_rec.python.protos.tower_pb2'
  # @@protoc_insertion_point(class_scope:protos.BayesTaskTower)
  ))
_sym_db.RegisterMessage(BayesTaskTower)


# @@protoc_insertion_point(module_scope)
