# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/variational_dropout.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/variational_dropout.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n0easy_rec/python/protos/variational_dropout.proto\x12\x06protos\"q\n\x17VariationalDropoutLayer\x12#\n\x15regularization_lambda\x18\x01 \x01(\x02:\x04\x30.01\x12\x31\n\"embedding_wise_variational_dropout\x18\x02 \x01(\x08:\x05\x66\x61lse')
)




_VARIATIONALDROPOUTLAYER = _descriptor.Descriptor(
  name='VariationalDropoutLayer',
  full_name='protos.VariationalDropoutLayer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='regularization_lambda', full_name='protos.VariationalDropoutLayer.regularization_lambda', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.01),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='embedding_wise_variational_dropout', full_name='protos.VariationalDropoutLayer.embedding_wise_variational_dropout', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=173,
)

DESCRIPTOR.message_types_by_name['VariationalDropoutLayer'] = _VARIATIONALDROPOUTLAYER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VariationalDropoutLayer = _reflection.GeneratedProtocolMessageType('VariationalDropoutLayer', (_message.Message,), dict(
  DESCRIPTOR = _VARIATIONALDROPOUTLAYER,
  __module__ = 'easy_rec.python.protos.variational_dropout_pb2'
  # @@protoc_insertion_point(class_scope:protos.VariationalDropoutLayer)
  ))
_sym_db.RegisterMessage(VariationalDropoutLayer)


# @@protoc_insertion_point(module_scope)
