# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: easy_rec/python/protos/wide_and_deep.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from easy_rec.python.protos import dnn_pb2 as easy__rec_dot_python_dot_protos_dot_dnn__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='easy_rec/python/protos/wide_and_deep.proto',
  package='protos',
  syntax='proto2',
  serialized_pb=_b('\n*easy_rec/python/protos/wide_and_deep.proto\x12\x06protos\x1a easy_rec/python/protos/dnn.proto\"\x86\x01\n\x0bWideAndDeep\x12\x1a\n\x0fwide_output_dim\x18\x01 \x02(\r:\x01\x31\x12\x18\n\x03\x64nn\x18\x02 \x02(\x0b\x32\x0b.protos.DNN\x12\x1e\n\tfinal_dnn\x18\x03 \x01(\x0b\x32\x0b.protos.DNN\x12!\n\x11l2_regularization\x18\x04 \x01(\x02:\x06\x30.0001')
  ,
  dependencies=[easy__rec_dot_python_dot_protos_dot_dnn__pb2.DESCRIPTOR,])




_WIDEANDDEEP = _descriptor.Descriptor(
  name='WideAndDeep',
  full_name='protos.WideAndDeep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wide_output_dim', full_name='protos.WideAndDeep.wide_output_dim', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dnn', full_name='protos.WideAndDeep.dnn', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='final_dnn', full_name='protos.WideAndDeep.final_dnn', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='l2_regularization', full_name='protos.WideAndDeep.l2_regularization', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.0001),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=223,
)

_WIDEANDDEEP.fields_by_name['dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
_WIDEANDDEEP.fields_by_name['final_dnn'].message_type = easy__rec_dot_python_dot_protos_dot_dnn__pb2._DNN
DESCRIPTOR.message_types_by_name['WideAndDeep'] = _WIDEANDDEEP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WideAndDeep = _reflection.GeneratedProtocolMessageType('WideAndDeep', (_message.Message,), dict(
  DESCRIPTOR = _WIDEANDDEEP,
  __module__ = 'easy_rec.python.protos.wide_and_deep_pb2'
  # @@protoc_insertion_point(class_scope:protos.WideAndDeep)
  ))
_sym_db.RegisterMessage(WideAndDeep)


# @@protoc_insertion_point(module_scope)
